FROM node:18.14.2 AS builder
RUN mkdir -p /app
WORKDIR /app
ADD . .

RUN npm uninstall bcrypt
RUN npm install bcrypt
RUN npm install
RUN npm run build

ARG STAGE
ENV STAGE ${STAGE}
ARG POSTGRES_HOST
ENV POSTGRES_HOST ${POSTGRES_HOST}
ARG POSTGRES_PORT
ENV POSTGRES_PORT ${POSTGRES_PORT}
ARG POSTGRES_DATABASE
ENV POSTGRES_DATABASE ${POSTGRES_DATABASE}
ARG POSTGRES_USERNAME
ENV POSTGRES_USERNAME ${POSTGRES_USERNAME}
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ARG AWS_S3_BUCKET
ENV AWS_S3_BUCKET ${AWS_S3_BUCKET}
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ARG FRONTEND_URL
ENV FRONTEND_URL ${FRONTEND_URL}
ARG SWAGGER_USER
ENV SWAGGER_USER ${SWAGGER_USER}
ARG SWAGGER_PASSWORD
ENV SWAGGER_PASSWORD ${SWAGGER_PASSWORD}
ARG SENTRY_DSN
ENV SENTRY_DSN ${SENTRY_DSN}
ARG SLACK_WEBHOOK
ENV SLACK_WEBHOOK ${SLACK_WEBHOOK}
ARG EMAIL_USER
ENV EMAIL_USER ${EMAIL_USER}
ARG EMAIL_PASSWORD
ENV EMAIL_PASSWORD ${EMAIL_PASSWORD}
ARG EMAIL_FROM
ENV EMAIL_FROM ${EMAIL_FROM}
ARG EMAIL_TO
ENV EMAIL_TO ${EMAIL_TO}
ARG SWAGGER_USER
ENV SWAGGER_USER ${SWAGGER_USER}
ARG SWAGGER_PASSWORD
ENV SWAGGER_PASSWORD ${SWAGGER_PASSWORD}

CMD npm run start:prod
